name: Convert .ipynb to .py

on:
  push:
    paths:
      - '**.ipynb'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install nbconvert
      run: |
        pip install nbconvert

    - name: Convert notebooks to .py
      run: |
        for nb in $(find . -name "*.ipynb"); do
          echo "Converting $nb"
          jupyter nbconvert --to script "$nb"
          # Get base name without extension
          base=$(basename "$nb" .ipynb)
          # Check if output .py exists, then move or rename it
          if [ -f "${base}.py" ]; then
            echo "OutputFile file already exists. Renaming ${base}.py to custom_${base}.py"
            mv "${base}.py" "custom_${base}.py"
          fi
        done

    - name: Push converted files back
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git add .
        git commit -m "Auto-convert .ipynb to .py [skip ci]" || echo "No changes to commit"
        git push
